---
# tasks file for roles/aws
#
- name: "Fail when a mandatory extra vars are not defined"
  fail:
    msg: "AWS neccesary variable is not included"
  when:
    - project is not defined
    - action is not defined
    - subnet is not defined
    - vpc_id is not defined

- block:
    - import_tasks: add-net.yml
  when: action == "add"

- block:
    - import_tasks: delete-net.yml
  when: action == "delete"
